name: Keep Aternos Awake
name: Keep Aternos Awake
on:
  workflow_dispatch: # <--- THIS ENABLES THE MANUAL RUN BUTTON
  schedule:
    - cron: '*/5 * * * *'


jobs:
  ping-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run Bot Login
        run: node bot.js
        env:
          CI: true
